app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

com/urls.py
from django.urls import path

from com import views

app_name = 'com'

urlpatterns = [ 
    path('fetch_sensor_values_ajax', views.fetch_sensor_values_ajax, name='fetch_sensor_values_ajax'),
    path('fetch_sensor_values_ajax2', views.fetch_sensor_values_ajax2, name='fetch_sensor_values_ajax2'),
    path('fetch_sensor_values_ajax3', views.fetch_sensor_values_ajax3, name='fetch_sensor_values_ajax3'),
    path('fetch_sensor_values_ajax4', views.fetch_sensor_values_ajax4, name='fetch_sensor_values_ajax4'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from alertas.views import Alertas
from registros.views import Reg

urlpatterns = [

    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")), 
    path('',include('com.urls',namespace='com')),
    path('',include("registros.urls")),
    
    
 
  
    
   
   
               # UI Kits Html files
]

core/templates/page-403.html
{% extends "layouts/base.html" %}

{% block title %} 403 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<div class="content">
		<div class="page-inner">
			<div class="page-header">
				<h4 class="page-title">Home</h4>
				<ul class="breadcrumbs">
					<li class="nav-home">
						<a href="/">
							<i class="flaticon-home"></i>
						</a>
					</li>
					<li class="separator">
						<i class="flaticon-right-arrow"></i>
					</li>
					<li class="nav-item">
						<a href="#">Error 403</a>
					</li>
				</ul>
			</div>
			<div class="page-category">
                <h2>Error 403</h2>
                <h3 class="font-weight-light">
                    Access denied - Please <a href="{% url 'login' %}">authenticate</a>.
                </h3>
            </div>
		</div>
	</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-404.html
{% extends "layouts/base.html" %}

{% block title %} 404 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<div class="content">
		<div class="page-inner">
			<div class="page-header">
				<h4 class="page-title">Home</h4>
				<ul class="breadcrumbs">
					<li class="nav-home">
						<a href="/">
							<i class="flaticon-home"></i>
						</a>
					</li>
					<li class="separator">
						<i class="flaticon-right-arrow"></i>
					</li>
					<li class="nav-item">
						<a href="#">Error 404</a>
					</li>
				</ul>
			</div>
			<div class="page-category">
                <h2>Error 404</h2>
                <h3 class="font-weight-light">
                    The page you’re looking for was not found.
                </h3>
            </div>
		</div>
	</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/tables-simple.html
{% extends "layouts/base.html" %}

{% block title %} UI Datatables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content ">
	<div class="panel-header ">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
					<h5 class="text-white op-7 mb-2">Monitor de Sensores</h5>
				</div>
				<div class="ml-md-auto py-2 py-md-0">

				</div>
			</div>
		</div>
	</div>

	<div class="page-inner mt--5">
		<div class="row mt--2">

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="card-header">
							<h3 class="card-title">
								<i class="far fa-chart-bar"></i>
								Humedad de suelo
							</h3>
							<div class="card-tools">
								Real time
							</div>
						</div>

						<div class="card-body">
							<div id="chartContainer" style="height: 370px; width: 100%;"></div>
						</div>
						<div class="px-2 pb-2 pb-md-0 text-center">
							<div id="circles-1"></div>
							<h6 class="fw-bold mt-3 mb-0"> % Humedad de suelo</h6>
						</div>

						
						
						<form action="{% url 'reporte' %}" method="get">
							<button class="btn btn-default" type="submit">DESCARGAR REPORTE EN EXCEL</button>
						</form>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="table-responsive">
							<table id="add-row" class="display table table-striped table-hover">
								<thead>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</thead>
								<tfoot>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</tfoot>

								<tbody>
									{% for dato in data2 %}
									<tr>
										<td>{{dato.id}}</td>
										<td>{{dato.HoraFecha}}</td>
										<td>{{dato.h2}}</td>


									</tr>
									{% endfor %}

								</tbody>
							</table>
							
						</div>


					</div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="/static/assets/js/setting-demo2.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/3.1.0/firebase-database.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>
	
	
	
	$(document).ready(function () {
		$('#add-row').DataTable({
			"pageLength": 15,
		});
		$('#basic-datatables').DataTable({
			
		});
		
		
	});
	

	com = $("#comport").val();
	fill_graph_sensor(com);
	

	function fill_graph_sensor() {
		var dps = []; // dataPoints
		var chart = new CanvasJS.Chart("chartContainer", {
			animationEnabled: true,
			title: {
				text: "Gráfica Humedad de suelo vs Tiempo"
			},
			axisX: {
				title: "Tiempo"
			},
			axisY: {
				title: "Humedad Suelo %",
				suffix: "%"
			},
			data: [{
				type: "line",
				name: "CPU Utilization",
				connectNullData: true,
				//nullDataLineDashType: "solid",
				xValueType: "dateTime",
				xValueFormatString: "DD MMM hh:mm TT",
				yValueFormatString: "#,##0.##\"mm\"",
				dataPoints: dps
			}]
		});

		var xVal = 0;
		var yVal = 2000;
		var updateInterval = 1000;//miliseconds
		var dataLength = 720000; // number of dataPoints visible at any point
		var fecha1
		

		var updateChart = function () {

			$.ajax({
				type: "get",
				url: "{% url 'com:fetch_sensor_values_ajax' %}",
				data: {
					'id': com
				},
				success: function (data) {
					console.log(data.result);
					for (index = 0; index < data.result.length; index++) {
						var str_array = data.result[index].split(',');
					
						dps.push({
							x: Date.parse(str_array[1]),
							y: parseInt(str_array[0]),
						});
					}
					return data;
				},
				error: function () {
					console.log("error he ji");
				}
			});

			if (dps.length > dataLength) {
				dps.shift();
			}

			chart.render();
		};

		updateChart(dataLength);
		setInterval(function () { updateChart() }, updateInterval);
	}
	
	window.setTimeout(function () {
    location.href = "/Registros/";
	}, 28800000); // refresh/redirect after 5 seconds.
	
	
	var firebaseConfig = {
		apiKey: "AIzaSyDOzTjEfP9IjQrQ2MvALXpOYfFhgdmUAPM",
		authDomain: "cacaotech-50682.firebaseapp.com",
		databaseURL: "https://cacaotech-50682-default-rtdb.firebaseio.com",
		projectId: "cacaotech-50682",
		storageBucket: "cacaotech-50682.appspot.com",
		messagingSenderId: "595258699618",
		appId: "1:595258699618:web:aad60230ea12d4b5f7863b",
		measurementId: "G-PN438D53XE"
	};


	firebase.initializeApp(firebaseConfig);
	

	function update() {
		
		var data1 = "";
		firebase.database().ref('Data/id').once('value').then(

			function (snapshot) {
				globalThis.Humedad = snapshot.val().Humedad;
				globalThis.Temperatura = snapshot.val().Temperatura;
				globalThis.LDR = snapshot.val().LDR;
				globalThis.suelo = snapshot.val().suelo;
				globalThis.Motor = snapshot.val().Motor;
				console.table(Motor);

				Circles.create({
					id: 'circles-1',
					radius: 100,
					value: suelo,
					maxValue: 100,
					width: 5,
					text: suelo + '%',
					colors: ['#f1f1f1', '#2BB930'],
					duration: 0,
					wrpClass: 'circles-wrp',
					textClass: 'circles-text',
					styleWrapper: true,
					styleText: true
				})
				//console.log(title);
			})

		setTimeout(update, 1000)
	}
	update()
</script>

{% endblock javascripts %}

core/templates/tables-simple2.html
{% extends "layouts/base.html" %}

{% block title %} UI Datatables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content ">
	<div class="panel-header ">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
					<h5 class="text-white op-7 mb-2">Monitor de Sensores</h5>
				</div>
				<div class="ml-md-auto py-2 py-md-0">

				</div>
			</div>
		</div>
	</div>

	<div class="page-inner mt--5">
		<div class="row mt--2">

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="card-header">
							<h3 class="card-title">
								<i class="far fa-chart-bar"></i>
								Temperatura Ambiental
							</h3>
							<div class="card-tools">
								Real time
							</div>
						</div>

						<div class="card-body">
							<div id="chartContainer" style="height: 370px; width: 100%;"></div>
						</div>
						<div class="px-2 pb-2 pb-md-0 text-center">
							<div id="circles-1"></div>
							<h6 class="fw-bold mt-3 mb-0"> Temperatura °C</h6>
						</div>
						<form action="{% url 'reporte2' %}" method="get">
							<button class="btn btn-default" type="submit">DESCARGAR REPORTE EN EXCEL</button>
						</form>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="table-responsive">
							<table id="add-row" class="display table table-striped table-hover">
								<thead>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</thead>
								<tfoot>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</tfoot>

								<tbody>
									{% for dato in data3 %}
									<tr>
										<td>{{dato.id}}</td>
										<td>{{dato.HoraFecha}}</td>
										<td>{{dato.t}}</td>


									</tr>
									{% endfor %}

								</tbody>
							</table>
							<button type="submit">Save</button>
						</div>


					</div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="/static/assets/js/setting-demo2.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/3.1.0/firebase-database.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>

	$(document).ready(function () {
		$('#add-row').DataTable({
			"pageLength": 15,
		});
		$('#basic-datatables').DataTable({

		});


	});


	com = $("#comport").val();
	fill_graph_sensor(com);


	function fill_graph_sensor() {
		var dps = []; // dataPoints
		var chart = new CanvasJS.Chart("chartContainer", {
			animationEnabled: true,
			title: {
				text: "Gráfica Temperatura vs Tiempo"
			},
			axisX: {
				title: "Tiempo"
			},
			axisY: {
				title: "Temperatura °C",
				suffix: "°C"
			},
			data: [{
				type: "line",
				name: "CPU Utilization",
				connectNullData: true,
				//nullDataLineDashType: "solid",
				xValueType: "dateTime",
				xValueFormatString: "DD MMM hh:mm TT",
				yValueFormatString: "#,##0.##\"mm\"",
				dataPoints: dps
			}]
		});

		var xVal = 0;
		var yVal = 100;
		var updateInterval = 1000;//miliseconds
		var dataLength = 720000; // number of dataPoints visible at any point

		var updateChart = function () {

			$.ajax({
				type: "get",
				url: "{% url 'com:fetch_sensor_values_ajax2' %}",
				data: {
					'id': com
				},
				success: function (data) {
					console.log(data.result);
					for (index = 0; index < data.result.length; index++) {
						var str_array = data.result[index].split(',');
						dps.push({
							x: Date.parse(str_array[1]),
							y: Temperatura
						});
					}
					return data;
				},
				error: function () {
					console.log("error he ji");
				}
			});

			if (dps.length > dataLength) {
				dps.shift();
			}

			chart.render();
		};

		updateChart(dataLength);
		setInterval(function () { updateChart() }, updateInterval);
	}

	window.setTimeout(function () {
		location.href = "/Registros2/";
	}, 28800000); // refresh/redirect after 5 seconds.


	var firebaseConfig = {
		apiKey: "AIzaSyDOzTjEfP9IjQrQ2MvALXpOYfFhgdmUAPM",
		authDomain: "cacaotech-50682.firebaseapp.com",
		databaseURL: "https://cacaotech-50682-default-rtdb.firebaseio.com",
		projectId: "cacaotech-50682",
		storageBucket: "cacaotech-50682.appspot.com",
		messagingSenderId: "595258699618",
		appId: "1:595258699618:web:aad60230ea12d4b5f7863b",
		measurementId: "G-PN438D53XE"
	};


	firebase.initializeApp(firebaseConfig);


	function update() {

		var data1 = "";
		firebase.database().ref('Data/id').once('value').then(

			function (snapshot) {
				globalThis.Humedad = snapshot.val().Humedad;
				globalThis.Temperatura = snapshot.val().Temperatura;
				globalThis.LDR = snapshot.val().LDR;
				globalThis.suelo = snapshot.val().suelo;
				globalThis.Motor = snapshot.val().Motor;
				console.table(Motor);

				Circles.create({
					id: 'circles-1',
					radius: 100,
					value: Temperatura, 
					maxValue: 100,
					width: 5,
					text: Temperatura + '°C',
					colors: ['#f1f1f1', '#2BB930'],
					duration: 0,
					wrpClass: 'circles-wrp',
					textClass: 'circles-text',
					styleWrapper: true,
					styleText: true
				})
				//console.log(title);
			})

		setTimeout(update, 1000)
	}
	update()
</script>

{% endblock javascripts %}

core/templates/tables-simple3.html
{% extends "layouts/base.html" %}

{% block title %} UI Datatables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content ">
	<div class="panel-header ">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
					<h5 class="text-white op-7 mb-2">Monitor de Sensores</h5>
				</div>
				<div class="ml-md-auto py-2 py-md-0">

				</div>
			</div>
		</div>
	</div>

	<div class="page-inner mt--5">
		<div class="row mt--2">

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="card-header">
							<h3 class="card-title">
								<i class="far fa-chart-bar"></i>
								Humedad Ambiental
							</h3>
							<div class="card-tools">
								Real time
							</div>
						</div>

						<div class="card-body">
							<div id="chartContainer" style="height: 370px; width: 100%;"></div>
						</div>
						<div class="px-2 pb-2 pb-md-0 text-center">
							<div id="circles-1"></div>
							<h6 class="fw-bold mt-3 mb-0"> Humedad %</h6>
						</div>
						<form action="{% url 'reporte3' %}" method="get">
							<button class="btn btn-default" type="submit">DESCARGAR REPORTE EN EXCEL</button>
						</form>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="table-responsive">
							<table id="add-row" class="display table table-striped table-hover">
								<thead>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</thead>
								<tfoot>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Humedad</th>

									</tr>
								</tfoot>

								<tbody>
									{% for dato in data4 %}
									<tr>
										<td>{{dato.id}}</td>
										<td>{{dato.HoraFecha}}</td>
										<td>{{dato.h}}</td>


									</tr>
									{% endfor %}

								</tbody>
							</table>
							
						</div>


					</div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="/static/assets/js/setting-demo2.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/3.1.0/firebase-database.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>

	$(document).ready(function () {
		$('#add-row').DataTable({
			"pageLength": 15,
		});
		$('#basic-datatables').DataTable({

		});


	});


	com = $("#comport").val();
	fill_graph_sensor(com);


	function fill_graph_sensor() {
		var dps = []; // dataPoints
		var chart = new CanvasJS.Chart("chartContainer", {
			animationEnabled: true,
			title: {
				text: "Gráfica Humedad vs Tiempo"
			},
			axisX: {
				title: "Tiempo"
			},
			axisY: {
				title: "Humedad %",
				suffix: "%"
			},
			data: [{
				type: "line",
				name: "CPU Utilization",
				connectNullData: true,
				//nullDataLineDashType: "solid",
				xValueType: "dateTime",
				xValueFormatString: "DD MMM hh:mm TT",
				yValueFormatString: "#,##0.##\"mm\"",
				dataPoints: dps
			}]
		});

		var xVal = 0;
		var yVal = 100;
		var updateInterval = 1000;//miliseconds
		var dataLength = 720000; // number of dataPoints visible at any point

		var updateChart = function () {

			$.ajax({
				type: "get",
				url: "{% url 'com:fetch_sensor_values_ajax3' %}",
				data: {
					'id': com
				},
				success: function (data) {
					console.log(data.result);
					for (index = 0; index < data.result.length; index++) {
						var str_array = data.result[index].split(',');
						dps.push({
							x: Date.parse(str_array[1]),
							y: Humedad
						});
					}
					return data;
				},
				error: function () {
					console.log("error");
				}
			});

			if (dps.length > dataLength) {
				dps.shift();
			}

			chart.render();
		};

		updateChart(dataLength);
		setInterval(function () { updateChart() }, updateInterval);
	}

	window.setTimeout(function () {
		location.href = "/Registros3/";
	}, 28800000); // refresh/redirect after 5 seconds.


	var firebaseConfig = {
		apiKey: "AIzaSyDOzTjEfP9IjQrQ2MvALXpOYfFhgdmUAPM",
		authDomain: "cacaotech-50682.firebaseapp.com",
		databaseURL: "https://cacaotech-50682-default-rtdb.firebaseio.com",
		projectId: "cacaotech-50682",
		storageBucket: "cacaotech-50682.appspot.com",
		messagingSenderId: "595258699618",
		appId: "1:595258699618:web:aad60230ea12d4b5f7863b",
		measurementId: "G-PN438D53XE"
	};


	firebase.initializeApp(firebaseConfig);


	function update() {

		var data1 = "";
		firebase.database().ref('Data/id').once('value').then(

			function (snapshot) {
				globalThis.Humedad = snapshot.val().Humedad;
				globalThis.Temperatura = snapshot.val().Temperatura;
				globalThis.LDR = snapshot.val().LDR;
				globalThis.suelo = snapshot.val().suelo;
				globalThis.Motor = snapshot.val().Motor;
				console.table(Motor);

				Circles.create({
					id: 'circles-1',
					radius: 100,
					value: Humedad, 
					maxValue: 100,
					width: 5,
					text: Humedad + '%',
					colors: ['#f1f1f1', '#2BB930'],
					duration: 0,
					wrpClass: 'circles-wrp',
					textClass: 'circles-text',
					styleWrapper: true,
					styleText: true
				})
				//console.log(title);
			})

		setTimeout(update, 1000)
	}
	update()
</script>

{% endblock javascripts %}

core/templates/tables-simple4.html
{% extends "layouts/base.html" %}

{% block title %} UI Datatables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content ">
	<div class="panel-header ">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
					<h5 class="text-white op-7 mb-2">Monitor de Sensores</h5>
				</div>
				<div class="ml-md-auto py-2 py-md-0">

				</div>
			</div>
		</div>
	</div>

	<div class="page-inner mt--5">
		<div class="row mt--2">

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="card-header">
							<h3 class="card-title">
								<i class="far fa-chart-bar"></i>
								Luz Ambiental
							</h3>
							<div class="card-tools">
								Real time
							</div>
						</div>

						<div class="card-body">
							<div id="chartContainer" style="height: 370px; width: 100%;"></div>
						</div>
						<div class="px-2 pb-2 pb-md-0 text-center">
							<div id="circles-1"></div>
							<h6 class="fw-bold mt-3 mb-0"> Luminosidad %</h6>
						</div>
						<form action="{% url 'reporte4' %}" method="get">
							<button class="btn btn-default" type="submit">DESCARGAR REPORTE EN EXCEL</button>
						</form>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-body">

						<div class="table-responsive">
							<table id="add-row" class="display table table-striped table-hover">
								<thead>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor de Luz</th>

									</tr>
								</thead>
								<tfoot>
									<tr>
										<th>Id</th>
										<th>Fecha y Hora:</th>
										<th>Valor de sensor Luz</th>

									</tr>
								</tfoot>

								<tbody>
									{% for dato in data4 %}
									<tr>
										<td>{{dato.id}}</td>
										<td>{{dato.HoraFecha}}</td>
										<td>{{dato.h2}}</td>
									</tr>
									{% endfor %}

								</tbody>
							</table>
							
						</div>


					</div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="/static/assets/js/setting-demo2.js"></script>
<script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/3.1.0/firebase-database.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>

	$(document).ready(function () {
		$('#add-row').DataTable({
			"pageLength": 15,
		});
		$('#basic-datatables').DataTable({

		});


	});


	com = $("#comport").val();
	fill_graph_sensor(com);


	function fill_graph_sensor() {
		var dps = []; // dataPoints
		var chart = new CanvasJS.Chart("chartContainer", {
			animationEnabled: true,
			title: {
				text: "Gráfica Luminosidad vs Tiempo"
			},
			axisX: {
				title: "Tiempo"
			},
			axisY: {
				title: "Luminosidad %",
				suffix: "%"
			},
			data: [{
				type: "line",
				name: "CPU Utilization",
				connectNullData: true,
				//nullDataLineDashType: "solid",
				xValueType: "dateTime",
				xValueFormatString: "DD MMM hh:mm TT",
				yValueFormatString: "#,##0.##\"mm\"",
				dataPoints: dps
			}]
		});

		var xVal = 0;
		var yVal = 100;
		var updateInterval = 1000;//miliseconds
		var dataLength = 720000; // number of dataPoints visible at any point

		var updateChart = function () {

			$.ajax({
				type: "get",
				url: "{% url 'com:fetch_sensor_values_ajax4' %}",
				data: {
					'id': com
				},
				success: function (data) {
					console.log(data.result);
					for (index = 0; index < data.result.length; index++) {
						var str_array = data.result[index].split(',');
						dps.push({
							x: Date.parse(str_array[1]),
							y: LDR
						});
					}
					return data;
				},
				error: function () {
					console.log("error");
				}
			});

			if (dps.length > dataLength) {
				dps.shift();
			}

			chart.render();
		};

		updateChart(dataLength);
		setInterval(function () { updateChart() }, updateInterval);
	}

	window.setTimeout(function () {
		location.href = "/Registros4/";
	}, 28800000); // refresh/redirect after 5 seconds.


	var firebaseConfig = {
		apiKey: "AIzaSyDOzTjEfP9IjQrQ2MvALXpOYfFhgdmUAPM",
		authDomain: "cacaotech-50682.firebaseapp.com",
		databaseURL: "https://cacaotech-50682-default-rtdb.firebaseio.com",
		projectId: "cacaotech-50682",
		storageBucket: "cacaotech-50682.appspot.com",
		messagingSenderId: "595258699618",
		appId: "1:595258699618:web:aad60230ea12d4b5f7863b",
		measurementId: "G-PN438D53XE"
	};


	firebase.initializeApp(firebaseConfig);


	function update() {

		var data1 = "";
		firebase.database().ref('Data/id').once('value').then(

			function (snapshot) {
				globalThis.Humedad = snapshot.val().Humedad;
				globalThis.Temperatura = snapshot.val().Temperatura;
				globalThis.LDR = snapshot.val().LDR;
				globalThis.suelo = snapshot.val().suelo;
				globalThis.Motor = snapshot.val().Motor;
				console.table(Motor);

				Circles.create({
					id: 'circles-1',
					radius: 100,
					value: LDR, 
					maxValue: 100,
					width: 5,
					text: LDR + '%',
					colors: ['#f1f1f1', '#2BB930'],
					duration: 0,
					wrpClass: 'circles-wrp',
					textClass: 'circles-text',
					styleWrapper: true,
					styleText: true
				})
				//console.log(title);
			})

		setTimeout(update, 1000)
	}
	update()
</script>

{% endblock javascripts %}